module.exports = [
    { name: 'global', siteUrl: 'www.executivecentre.com' },
    { name: 'zh-cn', siteUrl: 'www.executivecentre.com.cn' },
    { name: 'ko-kr', siteUrl: 'www.executivecentre.co.kr' },
    { name: 'zh-hk', siteUrl: 'www.executivecentre.com/zh-hk' },
    { name: 'zh-tw', siteUrl: 'www.executivecentre.com/zh-tw' },
    { name: 'ja-jp', siteUrl: 'www.executivecentre.com/ja-jp' },
    { name: 'en-hk', siteUrl: 'www.executivecentre.com/en-hk' },
    { name: 'en-cn', siteUrl: 'www.executivecentre.com/en-cn' },
    { name: 'en-tw', siteUrl: 'www.executivecentre.com/en-tw' },
    { name: 'en-jp', siteUrl: 'www.executivecentre.com/en-jp' },
    { name: 'en-kr', siteUrl: 'www.executivecentre.com/en-kr' },
    { name: 'en-sg', siteUrl: 'www.executivecentre.com/en-sg' },
    { name: 'en-au', siteUrl: 'www.executivecentre.com/en-au' },
    { name: 'en-in', siteUrl: 'www.executivecentre.com/en-in' },
    { name: 'en-id', siteUrl: 'www.executivecentre.com/en-id' },
    { name: 'en-lk', siteUrl: 'www.executivecentre.com/en-lk' },
    { name: 'en-ae', siteUrl: 'www.executivecentre.com/en-ae' },
];